/**
 * cc65c
 * Copyright (C) 2016 David Jolly
 *
 * cc65c is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * cc65c is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef CC65C_ASSEMBLER_LEXER_TYPE_H_
#define CC65C_ASSEMBLER_LEXER_TYPE_H_

#include "../../include/core/exception.h"

namespace cc65c {

	namespace assembler {

		#define CC65C_ASSEMBLER_LEXER_HEADER "[CC65C::ASSEMBLER::LEXER]"

#ifndef NDEBUG
		#define CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER CC65C_ASSEMBLER_LEXER_HEADER " "
#else
		#define CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER
#endif // NDEBUG

		enum {
			CC65C_ASSEMBLER_LEXER_EXCEPTION_EXPECTING_ALPHA = 0,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_EXPECTING_LITERAL,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_EXPECTING_LITERAL_CHARACTER_ESCAPE,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_EXPECTING_SCALAR,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_EXPECTING_SYMBOL,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_EXPECTING_TOKEN,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_INVALID_LABEL,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_INVALID_LITERAL_CHARACTER,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_INVALID_LITERAL_CHARACTER_ESCAPE,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_INVALID_SCALAR,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_INVALID_SCALAR_BINARY,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_INVALID_SCALAR_OCTAL,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_INVALID_SYMBOL,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_NO_NEXT_TOKEN,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_NO_PREVIOUS_TOKEN,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_COMMENT,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_LITERAL_CHARACTER,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_LITERAL_CHARACTER_ESCAPE,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_LITERAL_STRING,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_SCALAR,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_SCALAR_BINARY,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_SCALAR_DECIMAL,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_SCALAR_HEXIDECIMAL,
			CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_SCALAR_OCTAL,
		};

		#define CC65C_ASSEMBLER_LEXER_EXCEPTION_MAX CC65C_ASSEMBLER_LEXER_EXCEPTION_UNTERMINATED_SCALAR_OCTAL

		static const std::string CC65C_ASSEMBLER_LEXER_EXCEPTION_STR[] = {
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Expecting alphanumeric",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Expecting character",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Expecting escape character",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Expecting scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Expecting symbol",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Expecting token",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Invalid label",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Invalid character",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Invalid escape character",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Invalid scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Invalid binary scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Invalid octal scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Invalid symbol",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "No next token in stream",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "No previous token in stream",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated comment",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated character",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated escape character",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated string",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated binary scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated decimal scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated hexidecimal scalar",
			CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER "Unterminated octal scalar",
			};

		#define CC65C_ASSEMBLER_LEXER_EXCEPTION_STRING(_TYPE_) \
			((_TYPE_) > CC65C_ASSEMBLER_LEXER_EXCEPTION_MAX ? CC65C_ASSEMBLER_LEXER_EXCEPTION_HEADER EXCEPTION_UNKNOWN : \
			STRING_CHECK(CC65C_ASSEMBLER_LEXER_EXCEPTION_STR[_TYPE_]))

		#define THROW_CC65C_ASSEMBLER_LEXER_EXCEPTION(_EXCEPT_) \
			THROW_EXCEPTION(CC65C_ASSEMBLER_LEXER_EXCEPTION_STRING(_EXCEPT_))
		#define THROW_CC65C_ASSEMBLER_LEXER_EXCEPTION_FORMAT(_EXCEPT_, _FORMAT_, ...) \
			THROW_EXCEPTION_FORMAT(CC65C_ASSEMBLER_LEXER_EXCEPTION_STRING(_EXCEPT_), \
				_FORMAT_, __VA_ARGS__)
	}
}

#endif // CC65C_ASSEMBLER_LEXER_TYPE_H_
